---
name: Intent

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Least-privilege default

defaults:
  run:
    shell: bash

jobs:
  intent:
    name: Intent
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read # Required to read repository commits.
      pull-requests: write # Required to post/update PR comments.
    steps:
      - name: Validate Intent
        uses: goeselt/intent@4ddbdcaca80e9eec590a81badeb0bc747fd65cbf # v1.3.0
        with:
          pr-comment: true
